### ISSUE TITLE
Rewrite the Dart library with models and better code comments

### ISSUE THREAD

**Issue by nashfive** [nashfive/phone_number#12]

**Comment by bassel** [comment]
Hello @nashfive, if you need someone to work on this issue I'd love to help. Rewriting the library with models will result in breaking changes which is why I thought of discussing them with you instead of implementing right away and opening a PR.  

## Proposed changes

- [ ] Adding a model called `PhoneNumber` to wrap the data returned by `parse` and `parseList`.
- [ ] Adding a model called `RegionInfo` to wrap the data returned by `allSupportedRegions`.
- [ ] Renaming `PhoneNumber` (the current class) to `PhoneNumberUtil` in order to distinguish it from the model. This naming is consistent with `PhoneNumberUtil` used inside [google/libphonenumber](https://github.com/google/libphonenumber).
- [ ] Introducing an enum called `PhoneNumberType` to be used instead of returning the type as a string.

Please let me know if these changes seem fine or if you'd like to tackle this change with a different apprach.

**Comment by nashfive** [comment]
Implemented in #32
