### ISSUE TITLE
middle east countries are always returning error

### ISSUE THREAD

**Issue by Johnny-Silverhand-47** [nashfive/phone_number#61]

**Comment by nashfive** [comment]
Hi @Johnny-Silverhand-47 

Sorry to hear that.. unfortunately, there is nothing I can do at the plugin level, since it's only an interface to the PhoneNumberKit library for iOS and the libphonenumber library for Android.

So I'd suggest to report the issue directly to the maintainers of the libphonenumber library, since the PhoneNumberKit relies on its metadata.
